image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:
  - docker-compose up -d
  - java -Dspring.datasource.url=jdbc:postgresql://localhost:5432/app -jar ./artifacts/aqa-shop.jar &

build_script:
  - chmod +x gradlew &
  - ./gradlew -Ddb.url=jdbc:postgresql://localhost:5432/app clean test -Dselenide.headless=true --info