image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:
  - docker compose up -d --build
  - java -Dspring.datasource.url=jdbc:mysql://localhost:3306/app -jar ./artifacts/aqa-shop.jar &

build_script:
  - ./gradlew -Ddb.url=jdbc:mysql://localhost:3306/app clean test